/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.los.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.los.controller.CustomerController;
import lk.ijse.los.modal.customer;

/**
 *
 * @author user
 */
public class DeleteCustomers extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomers
     */
    public DeleteCustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtTP = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtNic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel15.setText("Rent");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel14.setText("Bike");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 100));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel11.setText("Sol");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\Beautiful_Suzuki_GSX_R_Sport_Bike_Wallpaper.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 570));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 63, 63));
        jLabel1.setText("Delete Customer ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Customer NIC");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 370, 10));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Customer Full Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 180, -1));

        txtPName.setBorder(null);
        add(txtPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 330, 30));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 370, 10));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Mobile");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 60, -1));

        txtTP.setBorder(null);
        add(txtTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 320, 30));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 370, 10));

        txtNic.setBorder(null);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 310, 30));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("Address Line 1");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, -1));

        txtAddress1.setBorder(null);
        add(txtAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 360, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 370, 10));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Address Line 2");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        txtAddress2.setBorder(null);
        add(txtAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 360, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 370, 10));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("District");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        txtDistrict.setBorder(null);
        add(txtDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 360, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 370, 10));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("City");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        txtCity.setBorder(null);
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 370, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 380, 10));

        btnUpdate.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnUpdate.setText("Unregister Customer");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 170, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        if(txtNic.getText().trim().length()>0){

            try {

                customer OBJ=new CustomerController().getcustomer(txtNic.getText().trim());

                if(OBJ!=null){

                    txtAddress1.setText(OBJ.getAddress1());
                    txtAddress2.setText(OBJ.getAddress2());

                    txtCity.setText(OBJ.getCity());

                    txtDistrict.setText(OBJ.getDistrict());
                    txtPName.setText(OBJ.getCustomer_name());
                    txtTP.setText(OBJ.getMobile());

                }else{
                    JOptionPane.showMessageDialog(this, "No results Found","Warning",JOptionPane.WARNING_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DeleteCustomers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(DeleteCustomers.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            JOptionPane.showMessageDialog(this, "Please Insert an ID","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtNicActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
              if(txtNic.getText().trim().length()>1){
             try {
                 if (new CustomerController().dropcustomer(txtNic.getText().trim())) {
                     JOptionPane.showMessageDialog(null,"Deletetd...");
                 }else{
                     JOptionPane.showMessageDialog(null,"Something went Wrong!!!", "WARNING",JOptionPane.WARNING_MESSAGE);
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(DeleteCustomers.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(DeleteCustomers.class.getName()).log(Level.SEVERE, null, ex);
             }
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtTP;
    // End of variables declaration//GEN-END:variables
}
